CREATE TRIGGER account_BEFORE_UPDATE BEFORE UPDATE ON account FOR EACH ROW SET new.updated_at = UNIX_TIMESTAMP(NOW());

DELIMITER $$

CREATE TRIGGER account_BEFORE_INSERT
  BEFORE INSERT ON account FOR EACH ROW
BEGIN
  SET new.created_at = UNIX_TIMESTAMP(NOW()),
    new.updated_at = UNIX_TIMESTAMP(NOW());
END$$

DELIMITER ;
